[package]
name = "hbird-redemption-api-protobuf"
version = "0.6.1"
edition.workspace = true
authors = ["Anapaya & contributors"]
license = "Apache-2.0"
description = "Protobuf definitions for the Hummingbird redemption API"
repository = "https://github.com/anapaya/scion-sdk"
keywords = ["SCION", "networking"]

[dependencies]
# Local Dependencies
hbird-redemption-api-models = { workspace = true }
sciparse = { workspace = true }

# Global Dependencies
prost = { workspace = true }
prost-types = { workspace = true }
sha2 = { workspace = true }
rsa = { workspace = true }

[lints]
workspace = true
