// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RedemptionRequests {
    /// RedemptionRequest contains the reservation info (except the res_id), ingress and egress token.
    #[prost(message, repeated, tag = "1")]
    pub redemption: ::prost::alloc::vec::Vec<RedemptionRequest>,
    /// Client public key. 64 bytes.
    #[prost(bytes = "vec", tag = "2")]
    pub client_key: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RedemptionRequest {
    #[prost(message, optional, tag = "1")]
    pub red_info: ::core::option::Option<RedemptionInfo>,
    /// The asset redemption token for the ingress reservation. 16 bytes.
    #[prost(bytes = "vec", tag = "2")]
    pub ingress_token: ::prost::alloc::vec::Vec<u8>,
    /// The asset redemption token for the egress reservation. 16 bytes.
    #[prost(bytes = "vec", tag = "3")]
    pub egress_token: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Flyover {
    #[prost(message, optional, tag = "1")]
    pub red_info: ::core::option::Option<RedemptionInfo>,
    #[prost(message, optional, tag = "2")]
    pub reservation: ::core::option::Option<Reservation>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RedemptionInfo {
    /// Ingress ID. 16 bits.
    #[prost(uint32, tag = "1")]
    pub ingress: u32,
    /// Egress ID. 16 bits.
    #[prost(uint32, tag = "2")]
    pub egress: u32,
    /// Bandwidth. 16 bits.
    #[prost(uint32, tag = "3")]
    pub bw: u32,
    /// The unix timestamp when the reservation starts. 32 bits.
    #[prost(uint32, tag = "4")]
    pub start_time: u32,
    /// Duration in seconds. 16 bits.
    #[prost(uint32, tag = "5")]
    pub duration: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RedemptionResponses {
    #[prost(message, repeated, tag = "1")]
    pub reservation: ::prost::alloc::vec::Vec<Reservation>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Reservation {
    /// The ISD-AS for which the reservation is valid. 64 bits.
    #[prost(uint64, tag = "1")]
    pub ia: u64,
    /// Reservation ID, unique per AS. 32 bits.
    #[prost(uint32, tag = "2")]
    pub res_id: u32,
    /// The derived authentication key for the reservation. 16 bytes.
    #[prost(bytes = "vec", tag = "3")]
    pub auth_key: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StatusResponse {
    #[prost(uint32, tag = "1")]
    pub version: u32,
}
