[package]
name = "hbird-redemption-api-protobuf"
version = "0.5.2"
edition.workspace = true
authors = ["Anapaya & contributors"]
license = "Apache-2.0"
description = "Protobuf definitions for the Hummingbird redemption API"
repository = "https://github.com/anapaya/scion-sdk"
keywords = ["SCION", "networking"]

[dependencies]
# Local Dependencies
hbird-redemption-api-models = { workspace = true }
scion-proto = { workspace = true }

# Global Dependencies
chrono = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }

[lints]
workspace = true
