// Copyright 2026 Anapaya Systems
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Interop testing library to verify that SCION packets encoded by `sciparse` can be parsed by the
//! SCION protobuf library and vice versa.

use bytes::Bytes;
use proptest::{
    prelude::{Arbitrary, BoxedStrategy, Strategy},
    proptest,
    test_runner::Config,
};
use scion_proto::{
    packet::{PacketClassification, classify_scion_packet},
    scmp::ScmpMessageBase,
    wire_encoding::WireDecode,
};
use sciparse::{
    self,
    core::{encode::WireEncode, view::View},
    header::layout::ScionHeaderLayout,
    packet::{
        classify::{ClassifiedPacket, ptest::ArbitraryClassifiedPacketParams},
        model::ScionRawPacket,
        view::ScionRawPacketView,
    },
    payload::scmp::model::ptest::ArbitraryScmpMessageParams,
};

/// A wrapper around `ClassifiedPacket` that implements `Arbitrary` with parameters that generate
/// only packets that are compatible with the SCION proto library.
#[derive(Clone, Debug)]
struct CompatibleClassifiedPacket {
    pkt: ClassifiedPacket,
}
impl Arbitrary for CompatibleClassifiedPacket {
    type Parameters = ();
    type Strategy = BoxedStrategy<Self>;

    fn arbitrary_with(_: Self::Parameters) -> Self::Strategy {
        let cfg = ArbitraryClassifiedPacketParams {
            scmp_params: ArbitraryScmpMessageParams {
                unknown: 0,
                ..Default::default()
            },
            ..Default::default()
        };

        ClassifiedPacket::arbitrary_with(cfg)
            .prop_map(|case| CompatibleClassifiedPacket { pkt: case })
            .boxed()
    }
}

/// Compare packets generated by `sciparse` and parsed with the SCION proto library, and vice versa.
#[test]
fn sciparse_scionproto_interop() {
    proptest!(
        Config::with_cases(10_000),
        |(case: CompatibleClassifiedPacket)| {
            test_impl(case.pkt);
        }
    );

    fn test_impl(sciparse_packet: ClassifiedPacket) {
        let original_buf = sciparse_packet
            .encode_to_vec()
            .expect("Encoding packet failed");
        let (view, _) = ScionRawPacketView::from_slice(&original_buf)
            .expect("Parsing packet with sciparse failed");

        let recreated_sciparse_packet = ScionRawPacket::from_view(view)
            .expect("Converting sciparse packet view to proto packet failed")
            .classify()
            .unwrap();

        assert_eq!(sciparse_packet, recreated_sciparse_packet);

        let mut bytes = Bytes::from_owner(original_buf.to_vec());
        let scion_proto_packet = scion_proto::packet::ScionPacketRaw::decode(&mut bytes)
            .expect("Parsing packet with scion-proto failed");

        let classified_proto_packet = classify_scion_packet(scion_proto_packet)
            .expect("Classifying packet with scion-proto failed");

        // The classified packet type from sciparse should match the classified packet from
        // scion-proto, otherwise the test is not valid
        match (&sciparse_packet, &classified_proto_packet) {
            (ClassifiedPacket::Other(_), PacketClassification::Other(_)) => {}
            (
                ClassifiedPacket::Scmp(_),
                PacketClassification::ScmpWithoutDestination(_)
                | PacketClassification::ScmpWithDestination(..),
            ) => {}
            (ClassifiedPacket::Udp(_), PacketClassification::Udp(_)) => {}
            _ => panic!("Packet types do not match"),
        }

        // The re-encoded packet from scion-proto should match the original buffer from sciparse.
        let proto_buf = classified_proto_packet.encode_to_vec();
        if proto_buf != original_buf {
            let layout = ScionHeaderLayout::from_loaded(sciparse_packet.header());

            println!("Pkt {:#?}", sciparse_packet);

            let mut out = String::new();
            layout
                .annotations()
                .fmt_on_buffer(&mut out, &original_buf, 4)
                .expect("Formatting annotations failed");
            println!("SciParse:\n{}", out);

            let mut out = String::new();
            layout
                .annotations()
                .fmt_on_buffer(&mut out, &proto_buf, 4)
                .expect("Formatting annotations failed");
            println!("SciProto:\n{}", out);

            panic!("Re-encoded packet does not match original");
        }

        compare_models(&sciparse_packet, &classified_proto_packet);
    }
}

/// Compares each structural part of a sciparse `ClassifiedPacket` against a scion-proto
/// `PacketClassification`, validating that both libraries produce equivalent model representations
/// from the same wire bytes.
///
/// The comparison proceeds layer by layer:
///   Raw -> Header -> Common, Address, Path -> Standard path segments, ...
///   Raw -> Payload -> UDP / SCMP variants
fn compare_models(sciparse: &ClassifiedPacket, scion_proto: &PacketClassification) {
    let sp_header = sciparse.header();

    match (sciparse, scion_proto) {
        (ClassifiedPacket::Udp(sci_udp), PacketClassification::Udp(proto_udp)) => {
            compare_headers(sp_header, &proto_udp.headers);
            compare_udp_payload(&sci_udp.payload, &proto_udp.datagram);
        }
        (
            ClassifiedPacket::Scmp(sci_scmp),
            PacketClassification::ScmpWithDestination(_, proto_scmp)
            | PacketClassification::ScmpWithoutDestination(proto_scmp),
        ) => {
            compare_headers(sp_header, &proto_scmp.headers);
            compare_scmp_payload(&sci_scmp.payload, &proto_scmp.message);
        }
        (ClassifiedPacket::Other(sci_raw), PacketClassification::Other(proto_raw)) => {
            compare_headers(sp_header, &proto_raw.headers);
            assert_eq!(
                sci_raw.payload.as_slice(),
                proto_raw.payload.as_ref(),
                "Raw payload mismatch"
            );
        }
        _ => {
            panic!(
                "Packet classification mismatch: sciparse={:?} vs scion-proto={:?}",
                std::mem::discriminant(sciparse),
                std::mem::discriminant(scion_proto),
            )
        }
    }
}

// ------------------------------------------------------------------------------------------------
// Header comparison
// ------------------------------------------------------------------------------------------------

fn compare_headers(
    sci: &sciparse::header::model::ScionPacketHeader,
    proto: &scion_proto::packet::ScionHeaders,
) {
    compare_common_header(&sci.common, &proto.common);
    compare_address_header(&sci.address, &proto.address);
    compare_path(&sci.path, &proto.path);
}

fn compare_common_header(
    sci: &sciparse::header::model::CommonHeader,
    proto: &scion_proto::packet::CommonHeader,
) {
    assert_eq!(
        sci.traffic_class, proto.traffic_class,
        "traffic_class mismatch"
    );
    assert_eq!(sci.flow_id, proto.flow_id.get(), "flow_id mismatch");
    assert_eq!(sci.next_header, proto.next_header, "next_header mismatch");
}

fn compare_address_header(
    sci: &sciparse::header::model::AddressHeader,
    proto: &scion_proto::packet::AddressHeader,
) {
    // ISD-AS comparison
    assert_eq!(sci.dst_ia.0, proto.ia.destination.0, "dst ISD-AS mismatch");
    assert_eq!(sci.src_ia.0, proto.ia.source.0, "src ISD-AS mismatch");

    // Host address comparison
    compare_host_addr(&sci.dst_host_addr, &proto.host.destination, "dst");
    compare_host_addr(&sci.src_host_addr, &proto.host.source, "src");
}

fn compare_host_addr(
    sci: &sciparse::address::host_addr::WireHostAddr,
    proto: &scion_proto::wire_encoding::MaybeEncoded<
        scion_proto::address::HostAddr,
        (
            scion_proto::packet::AddressInfo,
            scion_proto::packet::RawHostAddress,
        ),
    >,
    label: &str,
) {
    use scion_proto::{address::HostAddr, wire_encoding::MaybeEncoded};
    use sciparse::address::host_addr::WireHostAddr;

    match (sci, proto) {
        (WireHostAddr::V4(sci_v4), MaybeEncoded::Decoded(HostAddr::V4(proto_v4))) => {
            assert_eq!(sci_v4, proto_v4, "{label} IPv4 host address mismatch");
        }
        (WireHostAddr::V6(sci_v6), MaybeEncoded::Decoded(HostAddr::V6(proto_v6))) => {
            assert_eq!(sci_v6, proto_v6, "{label} IPv6 host address mismatch");
        }
        (WireHostAddr::Svc(sci_svc), MaybeEncoded::Decoded(HostAddr::Svc(proto_svc))) => {
            assert_eq!(sci_svc.0, proto_svc.0, "{label} Svc host address mismatch");
        }
        (WireHostAddr::Unknown { id: _, bytes }, MaybeEncoded::Encoded((info, raw_bytes))) => {
            let expected_len = info.address_length();
            assert_eq!(
                bytes.as_slice(),
                &raw_bytes[..expected_len],
                "{label} Unknown host address bytes mismatch"
            );
        }
        _ => {
            panic!("{label} host address type mismatch: sciparse={sci:?} vs scion-proto={proto:?}")
        }
    }
}

// ------------------------------------------------------------------------------------------------
// Path comparison
// ------------------------------------------------------------------------------------------------

fn compare_path(sci: &sciparse::path::model::Path, proto: &scion_proto::path::DataPlanePath) {
    use scion_proto::path::DataPlanePath;
    use sciparse::path::model::Path;

    match (sci, proto) {
        (Path::Empty, DataPlanePath::EmptyPath) => {}
        (Path::Standard(sci_std), DataPlanePath::Standard(proto_enc)) => {
            compare_standard_path(sci_std, proto_enc);
        }
        (
            Path::Unsupported {
                path_type: sci_pt,
                data: sci_data,
            },
            DataPlanePath::Unsupported {
                path_type: proto_pt,
                bytes: proto_bytes,
            },
        ) => {
            assert_eq!(
                u8::from(*sci_pt),
                u8::from(*proto_pt),
                "Unsupported path type mismatch"
            );
            assert_eq!(
                sci_data.as_slice(),
                proto_bytes.as_ref(),
                "Unsupported path data mismatch"
            );
        }
        (Path::Hummingbird(sci_hbird), DataPlanePath::Hummingbird(proto_hbird)) => {
            compare_hbird_path(sci_hbird, proto_hbird);
        }
        (Path::OneHop(_), DataPlanePath::Unsupported { .. }) => {
            // scion-proto treats OneHop as unsupported, so we just compare raw bytes
            // via the top-level re-encode check.
        }
        _ => {
            panic!(
                "Path type mismatch: sciparse={:?} vs scion-proto={:?}",
                sci.path_type(),
                proto.path_type()
            )
        }
    }
}

fn compare_standard_path(
    sci: &sciparse::path::standard::model::StandardPath,
    proto_enc: &scion_proto::path::EncodedStandardPath,
) {
    let meta = proto_enc.meta_header();

    // Meta header
    assert_eq!(
        sci.current_info_field,
        meta.current_info_field.get(),
        "current_info_field mismatch"
    );
    assert_eq!(
        sci.current_hop_field,
        meta.current_hop_field.get(),
        "current_hop_field mismatch"
    );

    let (seg0, seg1, seg2) = sci.segment_lengths();
    assert_eq!(
        seg0,
        meta.segment_lengths[0].get(),
        "segment_lengths[0] mismatch"
    );
    assert_eq!(
        seg1,
        meta.segment_lengths[1].get(),
        "segment_lengths[1] mismatch"
    );
    assert_eq!(
        seg2,
        meta.segment_lengths[2].get(),
        "segment_lengths[2] mismatch"
    );

    // Decode the encoded path to get info/hop fields for detailed comparison
    let mut raw = bytes::Bytes::copy_from_slice(proto_enc.raw());
    let decoded = scion_proto::path::StandardPath::decode(&mut raw)
        .expect("Failed to decode standard path from scion-proto");

    // Info fields
    assert_eq!(
        sci.segments.len(),
        decoded.info_fields.len(),
        "info field count mismatch"
    );
    for (i, (sci_seg, proto_info)) in sci
        .segments
        .iter()
        .zip(decoded.info_fields.iter())
        .enumerate()
    {
        let sci_info = &sci_seg.info_field;
        compare_info_field(sci_info, proto_info, i);
    }

    // Hop fields
    let sci_hops: Vec<_> = sci
        .segments
        .iter()
        .flat_map(|s| s.hop_fields.iter())
        .collect();
    assert_eq!(
        sci_hops.len(),
        decoded.hop_fields.len(),
        "hop field count mismatch"
    );
    for (i, (sci_hop, proto_hop)) in sci_hops.iter().zip(decoded.hop_fields.iter()).enumerate() {
        compare_hop_field(sci_hop, proto_hop, i);
    }
}

fn compare_info_field(
    sci: &sciparse::path::standard::model::InfoField,
    proto: &scion_proto::path::standard::InfoField,
    index: usize,
) {
    assert_eq!(
        sci.flags
            .contains(sciparse::path::standard::types::InfoFieldFlags::CONS_DIR),
        proto.cons_dir,
        "info_field[{index}].cons_dir mismatch"
    );
    assert_eq!(
        sci.flags
            .contains(sciparse::path::standard::types::InfoFieldFlags::PEERING),
        proto.peer,
        "info_field[{index}].peer mismatch"
    );
    assert_eq!(
        sci.segment_id, proto.seg_id,
        "info_field[{index}].seg_id mismatch"
    );
    assert_eq!(
        sci.timestamp, proto.timestamp_epoch,
        "info_field[{index}].timestamp mismatch"
    );
}

fn compare_hop_field(
    sci: &sciparse::path::standard::model::HopField,
    proto: &scion_proto::path::standard::StandardHopField,
    index: usize,
) {
    assert_eq!(
        sci.flags
            .contains(sciparse::path::standard::types::StdHopFieldFlags::CONS_EGRESS_ROUTER_ALERT),
        proto.egress_router_alert,
        "hop_field[{index}].egress_router_alert mismatch"
    );
    assert_eq!(
        sci.flags
            .contains(sciparse::path::standard::types::StdHopFieldFlags::CONS_INGRESS_ROUTER_ALERT),
        proto.ingress_router_alert,
        "hop_field[{index}].ingress_router_alert mismatch"
    );
    assert_eq!(
        sci.expiration_units, proto.exp_time,
        "hop_field[{index}].exp_time mismatch"
    );
    assert_eq!(
        sci.cons_ingress, proto.cons_ingress,
        "hop_field[{index}].cons_ingress mismatch"
    );
    assert_eq!(
        sci.cons_egress, proto.cons_egress,
        "hop_field[{index}].cons_egress mismatch"
    );
    assert_eq!(sci.mac.0, proto.mac, "hop_field[{index}].mac mismatch");
}

fn compare_hbird_path(
    sci: &sciparse::path::hbird::model::HummingbirdPath,
    proto_enc: &scion_proto::path::hummingbird::EncodedHummingbirdPath,
) {
    let meta = proto_enc.meta_header();

    // Meta header
    assert_eq!(
        sci.current_info_field,
        meta.current_info_field.get(),
        "current_info_field mismatch"
    );
    assert_eq!(
        sci.current_hop_field,
        meta.current_hop_field.encode(),
        "current_hop_field mismatch"
    );

    let (seg0, seg1, seg2) = sci.segment_lengths_bytes();
    assert_eq!(
        seg0,
        meta.segment_lengths[0].bytes(),
        "segment_lengths[0] mismatch"
    );
    assert_eq!(
        seg1,
        meta.segment_lengths[1].bytes(),
        "segment_lengths[1] mismatch"
    );
    assert_eq!(
        seg2,
        meta.segment_lengths[2].bytes(),
        "segment_lengths[2] mismatch"
    );
    assert_eq!(
        sci.base_timestamp,
        proto_enc.meta_header().base_timestamp.get(),
        "base_timestamp mismatch"
    );
    assert_eq!(
        sci.millis_timestamp,
        proto_enc.meta_header().millis_timestamp.get(),
        "millis_timestamp mismatch"
    );
    assert_eq!(
        sci.counter,
        proto_enc.meta_header().counter.get(),
        "counter mismatch"
    );

    // Decode the encoded path to get info/hop fields for detailed comparison
    let mut raw = bytes::Bytes::copy_from_slice(proto_enc.raw());
    let decoded = scion_proto::path::hummingbird::EncodedHummingbirdPath::decode(&mut raw)
        .expect("Failed to decode hbird path from scion-proto");

    // Info fields
    assert_eq!(
        sci.segments.len(),
        decoded.segments().count(),
        "info field count mismatch"
    );
    for (i, (sci_seg, proto_info)) in sci.segments.iter().zip(decoded.info_fields()).enumerate() {
        let sci_info = &sci_seg.info_field;
        compare_info_field(sci_info, &proto_info.into(), i);
    }

    // Hop fields
    let sci_hops: Vec<_> = sci
        .segments
        .iter()
        .flat_map(|s| s.hop_fields.iter())
        .collect();
    assert_eq!(
        sci_hops.len(),
        decoded.hop_fields().count(),
        "hop field count mismatch"
    );
    for (i, (&sci_hop, proto_hop)) in sci_hops
        .iter()
        .zip(decoded.hop_fields().map(|enc_hf| {
            let raw: &[u8] = if enc_hf.is_flyover() {
                <&scion_proto::path::hummingbird::EncodedFlyoverHopField>::try_from(enc_hf)
                    .unwrap()
                    .as_ref()
            } else {
                enc_hf.standard_hopfield_unchecked().as_ref()
            };
            let mut b = Bytes::copy_from_slice(raw);
            scion_proto::path::hummingbird::HummingbirdHopField::decode(&mut b).unwrap()
        }))
        .enumerate()
    {
        match (sci_hop, proto_hop.clone()) {
            (
                sciparse::path::hbird::model::HbirdHopField::Standard(sci_hf),
                scion_proto::path::hummingbird::HummingbirdHopField::Standard(proto_hf),
            ) => {
                compare_hop_field(sci_hf, &proto_hf, i);
            }
            (
                sciparse::path::hbird::model::HbirdHopField::Flyover(sci_hf),
                scion_proto::path::hummingbird::HummingbirdHopField::Flyover(proto_hf),
            ) => {
                assert_eq!(
                    sci_hf.flags.contains(
                        sciparse::path::standard::types::StdHopFieldFlags::CONS_EGRESS_ROUTER_ALERT
                    ),
                    proto_hf.egress_router_alert,
                    "hop_field[{i}].egress_router_alert mismatch"
                );
                assert_eq!(
                    sci_hf.flags
                        .contains(sciparse::path::standard::types::StdHopFieldFlags::CONS_INGRESS_ROUTER_ALERT),
                    proto_hf.ingress_router_alert,
                    "hop_field[{i}].ingress_router_alert mismatch"
                );
                assert_eq!(
                    sci_hf.expiration_units, proto_hf.exp_time,
                    "hop_field[{i}].exp_time mismatch"
                );
                assert_eq!(
                    sci_hf.cons_ingress, proto_hf.cons_ingress,
                    "hop_field[{i}].cons_ingress mismatch"
                );
                assert_eq!(
                    sci_hf.cons_egress, proto_hf.cons_egress,
                    "hop_field[{i}].cons_egress mismatch"
                );
                assert_eq!(
                    sci_hf.mac.0, proto_hf.aggregated_mac,
                    "hop_field[{i}].mac mismatch"
                );

                assert_eq!(
                    sci_hf.res_id, proto_hf.res_id,
                    "hop_field[{i}].res_id mismatch"
                );
                assert_eq!(
                    sci_hf.bw,
                    proto_hf.res_bw.encode(),
                    "hop_field[{i}].bw mismatch"
                );

                assert_eq!(
                    sci_hf.res_start_offset, proto_hf.res_start_offset,
                    "hop_field[{i}].res_start_offset mismatch"
                );
                assert_eq!(
                    sci_hf.res_duration, proto_hf.res_duration,
                    "hop_field[{i}].res_duration mismatch"
                );
            }
            _ => {
                panic!(
                    "hop_field[{i}] type mismatch: sciparse={sci_hop:?} vs scion-proto={proto_hop:?}"
                )
            }
        }
    }
}

// ------------------------------------------------------------------------------------------------
// Payload comparison
// ------------------------------------------------------------------------------------------------

fn compare_udp_payload(
    sci: &sciparse::payload::udp::model::UdpDatagram,
    proto: &scion_proto::datagram::UdpMessage,
) {
    assert_eq!(sci.src_port, proto.port.source, "UDP src_port mismatch");
    assert_eq!(
        sci.dst_port, proto.port.destination,
        "UDP dst_port mismatch"
    );
    assert_eq!(
        sci.payload.as_slice(),
        proto.payload.as_ref(),
        "UDP payload mismatch"
    );
}

fn compare_scmp_payload(
    sci: &sciparse::payload::scmp::model::ScmpMessage,
    proto: &scion_proto::scmp::ScmpMessage,
) {
    use scion_proto::scmp::ScmpMessage as ProtoScmp;
    use sciparse::payload::scmp::model::ScmpMessage as SciScmp;

    match (sci, proto) {
        (SciScmp::DestinationUnreachable(s), ProtoScmp::DestinationUnreachable(p)) => {
            assert_eq!(
                u8::from(s.code),
                u8::from(p.code),
                "SCMP DestUnreach code mismatch"
            );
            assert_eq!(
                s.get_offending_packet(),
                p.get_offending_packet().as_ref(),
                "SCMP DestUnreach offending_packet mismatch"
            );
        }
        (SciScmp::PacketTooBig(s), ProtoScmp::PacketTooBig(p)) => {
            assert_eq!(s.mtu, p.mtu, "SCMP PacketTooBig mtu mismatch");
            assert_eq!(
                s.get_offending_packet(),
                p.get_offending_packet().as_ref(),
                "SCMP PacketTooBig offending_packet mismatch"
            );
        }
        (SciScmp::ParameterProblem(s), ProtoScmp::ParameterProblem(p)) => {
            assert_eq!(
                u8::from(s.code),
                u8::from(p.code),
                "SCMP ParamProblem code mismatch"
            );
            assert_eq!(s.pointer, p.pointer, "SCMP ParamProblem pointer mismatch");
            assert_eq!(
                s.get_offending_packet(),
                p.get_offending_packet().as_ref(),
                "SCMP ParamProblem offending_packet mismatch"
            );
        }
        (SciScmp::ExternalInterfaceDown(s), ProtoScmp::ExternalInterfaceDown(p)) => {
            assert_eq!(
                s.isd_asn.0,
                u64::from(p.isd_asn),
                "SCMP ExtIfDown isd_asn mismatch"
            );
            assert_eq!(
                s.interface_id as u64, p.interface_id,
                "SCMP ExtIfDown interface_id mismatch"
            );
            assert_eq!(
                s.get_offending_packet(),
                p.get_offending_packet().as_ref(),
                "SCMP ExtIfDown offending_packet mismatch"
            );
        }
        (SciScmp::InternalConnectivityDown(s), ProtoScmp::InternalConnectivityDown(p)) => {
            assert_eq!(
                s.isd_asn.0,
                u64::from(p.isd_asn),
                "SCMP IntConnDown isd_asn mismatch"
            );
            assert_eq!(
                s.ingress_interface_id as u64, p.ingress_interface_id,
                "SCMP IntConnDown ingress_interface_id mismatch"
            );
            assert_eq!(
                s.egress_interface_id as u64, p.egress_interface_id,
                "SCMP IntConnDown egress_interface_id mismatch"
            );
            assert_eq!(
                s.get_offending_packet(),
                p.get_offending_packet().as_ref(),
                "SCMP IntConnDown offending_packet mismatch"
            );
        }
        (SciScmp::EchoRequest(s), ProtoScmp::EchoRequest(p)) => {
            assert_eq!(
                s.identifier, p.identifier,
                "SCMP EchoReq identifier mismatch"
            );
            assert_eq!(
                s.sequence_number, p.sequence_number,
                "SCMP EchoReq sequence_number mismatch"
            );
            assert_eq!(
                s.data.as_slice(),
                p.data.as_ref(),
                "SCMP EchoReq data mismatch"
            );
        }
        (SciScmp::EchoReply(s), ProtoScmp::EchoReply(p)) => {
            assert_eq!(
                s.identifier, p.identifier,
                "SCMP EchoReply identifier mismatch"
            );
            assert_eq!(
                s.sequence_number, p.sequence_number,
                "SCMP EchoReply sequence_number mismatch"
            );
            assert_eq!(
                s.data.as_slice(),
                p.data.as_ref(),
                "SCMP EchoReply data mismatch"
            );
        }
        (SciScmp::TracerouteRequest(s), ProtoScmp::TracerouteRequest(p)) => {
            assert_eq!(
                s.identifier, p.identifier,
                "SCMP TracerouteReq identifier mismatch"
            );
            assert_eq!(
                s.sequence_number, p.sequence_number,
                "SCMP TracerouteReq sequence_number mismatch"
            );
        }
        (SciScmp::TracerouteReply(s), ProtoScmp::TracerouteReply(p)) => {
            assert_eq!(
                s.identifier, p.identifier,
                "SCMP TracerouteReply identifier mismatch"
            );
            assert_eq!(
                s.sequence_number, p.sequence_number,
                "SCMP TracerouteReply sequence_number mismatch"
            );
            assert_eq!(
                s.isd_asn.0,
                u64::from(p.isd_asn),
                "SCMP TracerouteReply isd_asn mismatch"
            );
            assert_eq!(
                s.interface_id as u64, p.interface_id,
                "SCMP TracerouteReply interface_id mismatch"
            );
        }
        (SciScmp::Unknown(s), ProtoScmp::UnknownError(p)) => {
            assert_eq!(
                s.message_type,
                u8::from(p.message_type),
                "SCMP Unknown type mismatch"
            );
            assert_eq!(s.code, p.code, "SCMP Unknown code mismatch");
            // The sciparse Unknown stores message_specific_data (everything after the 4-byte
            // header), while scion-proto UnknownError stores it as payload (info+data blocks).
            assert_eq!(
                s.message_specific_data.as_slice(),
                p.payload.as_ref(),
                "SCMP Unknown payload mismatch"
            );
        }
        _ => {
            panic!(
                "SCMP message type mismatch: sciparse={:?} vs scion-proto={:?}",
                sci.message_type(),
                proto.get_type()
            )
        }
    }
}
