[package]
name = "hbird-redemption-api-models"
version = "0.6.1"
edition.workspace = true
authors = ["Anapaya & contributors"]
license = "Apache-2.0"
description = "Hummingbird redemption API models"
repository = "https://github.com/anapaya/scion-sdk"
keywords = ["SCION", "networking"]

[dependencies]
# Local Dependencies
sciparse = { workspace = true }
scion-stack = { workspace = true }
reqwest-connect-rpc = { workspace = true }
scion-connect-rpc = { workspace = true }
svc-resolution-models = { workspace = true }

# Global Dependencies
async-trait = { workspace = true }
thiserror = { workspace = true }
rsa = { workspace = true }

[lints]
workspace = true
